= Build Tool Detector
Little service which will detect what build tool you are using.

=== Build [[build]]

==== Pre-requisites
* link:https://golang.org/doc/install[Golang prerequisites] and `$GOPATH` setup.
NOTE: Stick to Golang version 10 because of link:https://github.com/goadesign/goa/pull/1548[goa and golang 11]. Have a look how link:https://github.com/moovweb/gvm[Go Version Manager] can help you simplifying configuration and management of different versions of Go.

* clone the repo in your GOPATH:
[source,bash]
----
$ git clone https://github.com/fabric8-services/build-tool-detector $GOPATH/src/github.com/fabric8-services/build-tool-detector
----
==== Setup
* Use `config-template.yml` as a template to create your own `config.yml` file with the appropriate environment variable values.
[source,bash]
----
$ cp config-template.yml config.yml
----
* You need to configure GH OAuth app to test it locally:

1. Go to https://github.com/settings/applications/new[OAuth app]
1. Create a new developer application, in the `Authorization callback URL`,
1. Enter the url `http://localhost:8099`.

You'll get a page with `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` that you should use in your `config.xml`:
```
github:
    clientID: "GITHUB_CLIENT_ID"
    clientSecret: "GITHUB_CLIENT_SECRET"
```
==== Build

[source,bash]
----
$ make build
----

This will perform following actions: fetch dependencies, generate Goa files from design folder, compile.
When in doubt just `make help`.

=== Test [[test]]

In order to continuously run the tests whenever code change occur execute following command from the root directory of the project:

[source,bash]
----
$ make test
----

and keep it running in the terminal.

=== Run [[run]]

Run the server:

[source,bash]
----
$ make run
----
