= Build Tool Detector
Little service which will detect what build tool you are using.

=== Build [[build]]

==== Pre-requisites
* link:https://golang.org/doc/install[Golang prerequisites] and `$GOPATH` setup.
NOTE: Stick to Golang version 10 because of link:https://github.com/goadesign/goa/pull/1548[goa and golang 11]. Have a look how link:https://github.com/moovweb/gvm[Go Version Manager] can help you simplifying configuration and management of different versions of Go.

* clone the repo in your GOPATH:
[source,bash]
----
$ git clone https://github.com/fabric8-services/build-tool-detector $GOPATH/src/github.com/fabric8-services/build-tool-detector
----
==== Build

[source,bash]
----
$ make build
----

This will perform following actions: fetch dependencies, generate Goa files from design folder, compile.
When in doubt just `make help`.

==== Usage
[source,bash]
----
$ export TOKEN=XXXX
$ curl -X GET "http://localhost:8099/api/detect/build/https%3A%2F%2Fgithub.com%2Ffabric8-launcher%2Flauncher-backend" -H "accept: application/vnd.goa.build.tool.detector+json" -H "Authorization: Bearer $TOKEN"
{"build-tool-type":"maven"}
----
where:

* TOKEN is your JWT token taken from link:https://prod-preview.openshift.io/[OpenShift.io prod-preview]
* and our parameter repo is: https://github.com/fabric8-launcher/launcher-backend

=== Test [[test]]

In order to continuously run the tests whenever code change occur execute following command from the root directory of the project:

[source,bash]
----
$ make test
----

and keep it running in the terminal.

=== Run [[run]]

Run the server:

[source,bash]
----
$ make run
----
> NOTE: Our service's configuration uses viper. To setup dependent service like fabric8-auth prod or prod-preview,
please check link:/config/configuration.go[configuration file] or
set env variable like `BUILD_TOOL_DETECTOR_AUTH_URI`